name: Daily Gold Rate
on:
  schedule:
    - cron: '30 3 * * *' # Runs at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:      # Allows you to click a button to test it immediately

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python gold_scraper.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
